services:
  geth:
    image: ethereum/client-go
    container_name: geth-sepolia
    restart: unless-stopped
    volumes:
      - ./geth-data:/root/.ethereum
      - ./jwt.hex:/jwt.hex:ro
    ports:
      - "8545:8545"
      - "30303:30303"
      - "8551:8551"
    command:
      [
        "--sepolia",
        "--http",
        "--http.addr=0.0.0.0",
        "--http.api=eth,net,web3",
        "--http.corsdomain=*",
        "--http.vhosts=*",
        "--ws",
        "--ws.addr=0.0.0.0",
        "--ws.api=eth,net,web3",
        "--syncmode=snap",
        "--authrpc.addr=0.0.0.0",
        "--authrpc.port=8551",
        "--authrpc.vhosts=*",
        "--authrpc.jwtsecret=/jwt.hex"
      ]

  lighthouse:
    image: sigp/lighthouse
    container_name: lighthouse-sepolia
    restart: unless-stopped
    depends_on:
      - geth
    volumes:
      - ./lighthouse-data:/root/.lighthouse
      - ./jwt.hex:/jwt.hex:ro
    ports:
      - "5052:5052"
    command:
      [
        "lighthouse",
        "bn",
        "--network", "sepolia",
        "--http",
        "--http-address=0.0.0.0",
        "--execution-endpoint", "http://geth:8551",
        "--execution-jwt", "/jwt.hex",
        "--checkpoint-sync-url", "https://sepolia.checkpoint-sync.ethpandaops.io"
      ]
