services:
  nethermind:
    image: nethermind/nethermind
    container_name: nethermind-sepolia
    restart: unless-stopped
    volumes:
      - ./nethermind-data:/nethermind/nethermind_db
      - ./jwt.hex:/nethermind/jwt.hex
    ports:
      - "8545:8545"   # RPC
      - "8551:8551"   # Engine API
      - "30303:30303" # P2P
    command:
      - --config=sepolia
      - --Network.DiscoveryPort=30303
      - --Network.P2PPort=30303
      - --JsonRpc.Enabled=true
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.Port=8545
      - --JsonRpc.EngineHost=0.0.0.0
      - --JsonRpc.EnginePort=8551
      - --JsonRpc.JwtSecretFile=/nethermind/jwt.hex
      - --Sync.FastSync=true
      - --Sync.SnapSync=true

  lighthouse:
    image: sigp/lighthouse
    container_name: lighthouse-sepolia
    restart: unless-stopped
    depends_on:
      - nethermind
    volumes:
      - ./lighthouse-data:/root/.lighthouse
      - ./jwt.hex:/jwt.hex:ro
    ports:
      - "5052:5052"
    command:
      [
        "lighthouse",
        "bn",
        "--network", "sepolia",
        "--http",
        "--http-address=0.0.0.0",
        "--execution-endpoint", "http://nethermind:8551",
        "--execution-jwt", "/jwt.hex",
        "--checkpoint-sync-url", "https://sepolia.checkpoint-sync.ethpandaops.io"
      ]
